name: Continuous Integration

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        dotnet-version: '5.0.x'
    
    - name: Setup .NET 5
      uses: xt0rted/setup-dotnet@v1.3.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build app
      run: dotnet build -c Release --no-restore



    



